/*
 * Copyright 2025 The libx Authors. All rights reserved.
 * Use of this source code is governed by a MIT license that can be
 * found in the LICENSE file.
 *
 * server_h2_test.cpp - HTTP/2 (h2c Prior Knowledge) unit tests for xhttp
 */

#include "server_test_helper.h"

#include <fcntl.h>
#include <poll.h>

#include <map>
#include <set>

#include <nghttp2/nghttp2.h>

/* ── H2 client helper ──────────────────────────────────────────────────── */

/**
 * Simple nghttp2 client session wrapper for testing.
 * Sends/receives H2 frames over a raw TCP socket.
 */
class H2Client {
public:
  H2Client() : session_(nullptr), fd_(-1) {}

  ~H2Client() {
    if (session_) nghttp2_session_del(session_);
    if (fd_ >= 0) close(fd_);
  }

  bool connect(uint16_t port) {
    fd_ = connect_to(port);
    if (fd_ < 0) return false;

    /* Set up nghttp2 client session */
    nghttp2_session_callbacks *callbacks;
    nghttp2_session_callbacks_new(&callbacks);
    nghttp2_session_callbacks_set_send_callback(callbacks, send_cb);
    nghttp2_session_callbacks_set_on_frame_recv_callback(callbacks, on_frame_recv_cb);
    nghttp2_session_callbacks_set_on_data_chunk_recv_callback(callbacks, on_data_chunk_cb);
    nghttp2_session_callbacks_set_on_header_callback(callbacks, on_header_cb);
    nghttp2_session_callbacks_set_on_stream_close_callback(callbacks, on_stream_close_cb);

    int rv = nghttp2_session_client_new(&session_, callbacks, this);
    nghttp2_session_callbacks_del(callbacks);
    if (rv != 0) return false;

    /* Send client connection preface (SETTINGS) */
    nghttp2_settings_entry settings[] = {
      {NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS, 100},
    };
    nghttp2_submit_settings(session_, NGHTTP2_FLAG_NONE, settings, 1);
    flush_session();

    return true;
  }

  /**
   * Submit a GET request and return the stream ID.
   */
  int32_t submit_get(const std::string &path) {
    std::string method_str    = "GET";
    std::string scheme_str    = "http";
    std::string authority_str = "localhost";
    nghttp2_nv  nva[]         = {
      make_nv(":method", method_str.c_str()),
      make_nv(":path", path.c_str()),
      make_nv(":scheme", scheme_str.c_str()),
      make_nv(":authority", authority_str.c_str()),
    };
    int32_t stream_id = nghttp2_submit_request(session_, nullptr, nva, 4, nullptr, nullptr);
    flush_session();
    return stream_id;
  }

  /**
   * Submit a POST request with body and return the stream ID.
   */
  int32_t submit_post(const std::string &path, const std::string &body) {
    std::string method_str    = "POST";
    std::string scheme_str    = "http";
    std::string authority_str = "localhost";
    std::string ct_str        = "text/plain";
    nghttp2_nv  nva[]         = {
      make_nv(":method", method_str.c_str()),  make_nv(":path", path.c_str()),
      make_nv(":scheme", scheme_str.c_str()),  make_nv(":authority", authority_str.c_str()),
      make_nv("content-type", ct_str.c_str()),
    };

    /* Data provider for the body */
    post_body_ = body;
    post_pos_  = 0;

    nghttp2_data_provider data_prd;
    data_prd.source.ptr    = this;
    data_prd.read_callback = post_read_cb;

    int32_t stream_id = nghttp2_submit_request(session_, nullptr, nva, 5, &data_prd, nullptr);
    flush_session();
    return stream_id;
  }

  /**
   * Perform I/O: send pending data and receive response data.
   * Call this in a loop with run_for.
   */
  void perform_io() {
    /* Send any pending data */
    flush_session();

    /* Read data from socket */
    char          buf[8192];
    struct pollfd pfd;
    pfd.fd     = fd_;
    pfd.events = POLLIN;

    while (poll(&pfd, 1, 10) > 0 && (pfd.revents & POLLIN)) {
      ssize_t n = recv(fd_, buf, sizeof(buf), 0);
      if (n <= 0) break;

      ssize_t rv = nghttp2_session_mem_recv(session_, reinterpret_cast<const uint8_t *>(buf),
                                            static_cast<size_t>(n));
      if (rv < 0) break;

      /* Send any frames generated by processing received data (e.g. SETTINGS
       * ACK) */
      flush_session();
    }
  }

  /* Response data accessors */
  int response_status(int32_t stream_id) const {
    auto it = responses_.find(stream_id);
    if (it != responses_.end()) return it->second.status;
    return 0;
  }

  std::string response_body(int32_t stream_id) const {
    auto it = responses_.find(stream_id);
    if (it != responses_.end()) return it->second.body;
    return "";
  }

  bool stream_closed(int32_t stream_id) const {
    return closed_streams_.count(stream_id) > 0;
  }

  std::string response_header(int32_t stream_id, const std::string &name) const {
    auto it = responses_.find(stream_id);
    if (it != responses_.end()) {
      auto hit = it->second.headers.find(name);
      if (hit != it->second.headers.end()) return hit->second;
    }
    return "";
  }

private:
  struct Response {
    int                                status = 0;
    std::string                        body;
    std::map<std::string, std::string> headers;
  };

  nghttp2_session            *session_;
  int                         fd_;
  std::map<int32_t, Response> responses_;
  std::set<int32_t>           closed_streams_;
  std::string                 post_body_;
  size_t                      post_pos_ = 0;

  void flush_session() {
    while (nghttp2_session_want_write(session_)) {
      int rv = nghttp2_session_send(session_);
      if (rv != 0) break;
    }
    /* Actually write to socket */
    /* nghttp2 send_callback already writes to fd_ */
  }

  static nghttp2_nv make_nv(const char *name, const char *value) {
    nghttp2_nv nv;
    nv.name     = reinterpret_cast<uint8_t *>(const_cast<char *>(name));
    nv.namelen  = strlen(name);
    nv.value    = reinterpret_cast<uint8_t *>(const_cast<char *>(value));
    nv.valuelen = strlen(value);
    nv.flags    = NGHTTP2_NV_FLAG_NONE;
    return nv;
  }

  /* nghttp2 send callback: write to socket */
  static ssize_t send_cb(nghttp2_session *session, const uint8_t *data, size_t length, int flags,
                         void *user_data) {
    (void)session;
    (void)flags;
    H2Client *self = reinterpret_cast<H2Client *>(user_data);
    ssize_t   n    = send(self->fd_, data, length, 0);
    if (n < 0) {
      if (errno == EAGAIN || errno == EWOULDBLOCK) return NGHTTP2_ERR_WOULDBLOCK;
      return NGHTTP2_ERR_CALLBACK_FAILURE;
    }
    return n;
  }

  /* nghttp2 frame recv callback */
  static int on_frame_recv_cb(nghttp2_session *session, const nghttp2_frame *frame,
                              void *user_data) {
    (void)session;
    (void)user_data;
    (void)frame;
    return 0;
  }

  /* nghttp2 data chunk callback */
  static int on_data_chunk_cb(nghttp2_session *session, uint8_t flags, int32_t stream_id,
                              const uint8_t *data, size_t len, void *user_data) {
    (void)session;
    (void)flags;
    H2Client *self = reinterpret_cast<H2Client *>(user_data);
    self->responses_[stream_id].body.append(reinterpret_cast<const char *>(data), len);
    return 0;
  }

  /* nghttp2 header callback */
  static int on_header_cb(nghttp2_session *session, const nghttp2_frame *frame, const uint8_t *name,
                          size_t namelen, const uint8_t *value, size_t valuelen, uint8_t flags,
                          void *user_data) {
    (void)session;
    (void)flags;
    H2Client *self = reinterpret_cast<H2Client *>(user_data);

    if (frame->hd.type != NGHTTP2_HEADERS) return 0;

    std::string n(reinterpret_cast<const char *>(name), namelen);
    std::string v(reinterpret_cast<const char *>(value), valuelen);

    if (n == ":status") {
      self->responses_[frame->hd.stream_id].status = std::stoi(v);
    } else {
      self->responses_[frame->hd.stream_id].headers[n] = v;
    }
    return 0;
  }

  /* nghttp2 stream close callback */
  static int on_stream_close_cb(nghttp2_session *session, int32_t stream_id, uint32_t error_code,
                                void *user_data) {
    (void)session;
    (void)error_code;
    H2Client *self = reinterpret_cast<H2Client *>(user_data);
    self->closed_streams_.insert(stream_id);
    return 0;
  }

  /* POST body read callback */
  static ssize_t post_read_cb(nghttp2_session *session, int32_t stream_id, uint8_t *buf,
                              size_t length, uint32_t *data_flags, nghttp2_data_source *source,
                              void *user_data) {
    (void)session;
    (void)stream_id;
    (void)user_data;
    H2Client *self      = reinterpret_cast<H2Client *>(source->ptr);
    size_t    remaining = self->post_body_.size() - self->post_pos_;
    size_t    to_copy   = std::min(remaining, length);

    if (to_copy > 0) {
      memcpy(buf, self->post_body_.data() + self->post_pos_, to_copy);
      self->post_pos_ += to_copy;
    }

    if (self->post_pos_ >= self->post_body_.size()) {
      *data_flags |= NGHTTP2_DATA_FLAG_EOF;
    }

    return static_cast<ssize_t>(to_copy);
  }
};

/* ── H2 Test Fixture ───────────────────────────────────────────────────── */

class HttpServerH2Test : public ::testing::Test {
protected:
  xEventLoop  loop   = nullptr;
  xHttpServer server = nullptr;
  xHttpMux    mux    = nullptr;
  uint16_t    port   = 0;

  void SetUp() override {
    loop = xEventLoopCreate();
    ASSERT_NE(loop, nullptr);
    xEventLoopEnter(loop);

    mux = xHttpMuxCreate();
    ASSERT_NE(mux, nullptr);

    xHttpServerConf conf = {};
    conf.resolve         = xHttpMuxResolve;
    conf.router          = mux;
    conf.idle_timeout_ms = 60000;

    server = xHttpServerCreate(&conf);
    ASSERT_NE(server, nullptr);

    port = find_free_port();
    ASSERT_NE(port, 0) << "Could not find a free port";
  }

  void TearDown() override {
    if (server) xHttpServerDestroy(server);
    if (mux) xHttpMuxDestroy(mux);
    xEventLoopLeave();
    if (loop) xEventLoopDestroy(loop);
  }

  void listen_and_pump() {
    xErrno err = xHttpServerListen(server, "127.0.0.1", port);
    ASSERT_EQ(err, xErrno_Ok) << "Failed to listen on port " << port;
    run_for(loop, 20);
  }

  void route(const char *pattern, xHttpDoneFunc on_done, void *arg = nullptr) {
    xHttpRouteConf conf = {};
    conf.pattern        = pattern;
    conf.on_done        = on_done;
    conf.arg            = arg;
    ASSERT_EQ(xHttpMuxHandle(mux, &conf), xErrno_Ok);
  }
};

/* ── H2 Tests ──────────────────────────────────────────────────────────── */

static void h2_hello_handler(xHttpCtx *ctx, void *arg) {
  (void)arg;
  xHttpCtxSetHeader(ctx, "content-type", "text/plain");
  xHttpCtxSend(ctx, "hello h2", 8);
}

TEST_F(HttpServerH2Test, PriorKnowledgeGetRequest) {
  route("GET /hello", h2_hello_handler);
  listen_and_pump();

  H2Client client;
  ASSERT_TRUE(client.connect(port));
  run_for(loop, 50);

  /* Perform initial I/O to exchange SETTINGS */
  client.perform_io();
  run_for(loop, 50);
  client.perform_io();
  run_for(loop, 50);

  /* Submit GET request */
  int32_t stream_id = client.submit_get("/hello");
  ASSERT_GT(stream_id, 0);

  /* Pump and perform I/O to get response */
  for (int i = 0; i < 20; i++) {
    run_for(loop, 25);
    client.perform_io();
    if (client.response_status(stream_id) > 0) break;
  }

  EXPECT_EQ(client.response_status(stream_id), 200);
  EXPECT_EQ(client.response_header(stream_id, "content-type"), "text/plain");
}

TEST_F(HttpServerH2Test, H2NotFoundReturns404) {
  listen_and_pump();

  H2Client client;
  ASSERT_TRUE(client.connect(port));
  run_for(loop, 50);

  client.perform_io();
  run_for(loop, 50);
  client.perform_io();
  run_for(loop, 50);

  int32_t stream_id = client.submit_get("/nonexistent");
  ASSERT_GT(stream_id, 0);

  for (int i = 0; i < 20; i++) {
    run_for(loop, 25);
    client.perform_io();
    if (client.response_status(stream_id) > 0) break;
  }

  EXPECT_EQ(client.response_status(stream_id), 404);
}

TEST_F(HttpServerH2Test, H1AndH2Coexist) {
  route("GET /hello", h2_hello_handler);
  listen_and_pump();

  /* First: H1 request */
  {
    int fd = connect_to(port);
    ASSERT_GE(fd, 0);
    std::string request = "GET /hello HTTP/1.1\r\nHost: localhost\r\n"
                          "Connection: close\r\n\r\n";
    ASSERT_TRUE(send_str(fd, request));
    run_for(loop, 100);
    std::string response = recv_all(fd);
    close(fd);
    EXPECT_NE(response.find("200 OK"), std::string::npos);
    EXPECT_NE(response.find("hello h2"), std::string::npos);
  }

  /* Second: H2 request on the same port */
  {
    H2Client client;
    ASSERT_TRUE(client.connect(port));
    run_for(loop, 50);
    client.perform_io();
    run_for(loop, 50);
    client.perform_io();
    run_for(loop, 50);

    int32_t stream_id = client.submit_get("/hello");
    ASSERT_GT(stream_id, 0);

    for (int i = 0; i < 20; i++) {
      run_for(loop, 25);
      client.perform_io();
      if (client.response_status(stream_id) > 0) break;
    }

    EXPECT_EQ(client.response_status(stream_id), 200);
  }
}
