[book]
title = "X Documentation"
description = "Foundation libraries for programming in C/C艹."
authors = ["mivinci"]
language = "en"
src = "."

[build]
build-dir = "../book"

[output.html]
git-repository-url = "https://github.com/mivinci/libx"
edit-url-template = "https://github.com/mivinci/libx/edit/main/docs/{path}"
additional-css = ["theme/custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.fold]
enable = true
level = 1
