FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates cmake g++ git make \
    libgtest-dev libnghttp2-dev libssl-dev libusrsctp-dev \
    libcurl4-openssl-dev libmbedtls-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
